### ISSUE TITLE
Long memory or chat with your own data

### ISSUE THREAD

**Issue by vazurg** [HexyeDEV/Telegram-Chatbot-Gpt4Free#3]
Hi. Is it possible to use own data to ask using langchain as in this repo https://github.com/techleadhd/chatgpt-retrieval ?

**Comment by HexyeDEV** [comment]
I'll try to work on that

**Comment by HexyeDEV** [comment]
With commit https://github.com/HexyeDEV/Telegram-Chatbot-Gpt4Free/commit/8fccdad117e22e7a8deaf0fcaef208aaea6e098c instead of using langchain that should be used with official openai api, I instead used a vector db, chromadb, to store long term memory in the bot. Memory must be enabled every time the bot is restarted with the command /memory #
